version: "3"
services:
  app:
    image: quake-report
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
